name: Masscan

on:
  workflow_dispatch:

jobs:
  scan:
    strategy:
      matrix:
        port: [443, 2053, 2083, 2087, 2096, 8443]

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y masscan jq

      - name: Scan
        run: |
          sudo masscan -p${{ matrix.port }} -iL input.txt --excludefile exclude.txt --rate 80000 2>/dev/null | bun check.js

      - name: Upload pxip.json
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: prxip-${{ matrix.port }}
          path: prxip.json
          if-no-files-found: ignore
          retention-days: 7
