name: Masscan ipverse ASN

on:
  workflow_dispatch:
    inputs:
      asn:
        description: 'Nomor ASN (tanpa prefix "AS", contoh: 13335 untuk Cloudflare)'
        required: true
        type: string

jobs:
  scan:
    strategy:
      matrix:
        port: [80, 8080, 8880, 2052, 2082, 2086, 2095, 443, 2053, 2083, 2087, 2096, 8443]

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y masscan jq

      - name: Download IP list
        env:
          ASN: ${{ inputs.asn }}
        run: |
          curl -fsSL \
            "https://raw.githubusercontent.com/ipverse/as-ip-blocks/refs/heads/master/as/${ASN}/aggregated.json" \
            | jq -r '.prefixes.ipv4[]' \
            > iplist.txt

          echo "ASN: AS${ASN}"
          echo "Total CIDR: $(wc -l < iplist.txt)"
          head -n 10 iplist.txt

      - name: Scan
        run: |
          sudo masscan \
            -p${{ matrix.port }} \
            -iL iplist.txt \
            --excludefile exclude.txt \
            --rate 80000 \
            2>/dev/null \
            | bun check.js

      - name: Upload IP list
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: iplist-as${{ inputs.asn }}-port-${{ matrix.port }}
          path: iplist.txt
          archive: false
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload prxip.json
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: prxip-as${{ inputs.asn }}-port-${{ matrix.port }}
          path: prxip.json
          archive: false
          if-no-files-found: ignore
          retention-days: 7
